# Header
menu:
  home: /
  archive: /archives
  Abc: /page
rss: /rss.xml

# Content
excerpt: true
fancybox: true

# Sidebar
## set the position of sidebar
sidebar: right
## sort widgets of sidebar from here
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- recent_comments
- links

# list of link
links:
- name: "Morris' Blog"
  site: "http://mypaper.pchome.com.tw/zerojudge"
  intro: "神 morris"
- name: "Morris' Blog (on Github)"
  site: "http://morris821028.github.io"

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
disqus_shortname: m80126colin